### ISSUE TITLE
"Unable to perform this operation" error

### ISSUE THREAD

**Issue by jasonlakez** [mrikirill/SynologyDDNSCloudflareMultidomain#42]
Seems it's the problem in the NAS configuration. Issue started after a IP change. Was working perfectly until yesterday.

![Untitled](https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain/assets/35470714/1e2598fe-07e5-4a52-82b6-463a4fcdc851)

**Comment by priitliivak** [comment]
Root cause seems to be: :"PATCH method not allowed for the api_token authentication scheme"

**Comment by gozzilli** [comment]
Found the same issue on a new install -- first time I use the tool.

**Comment by mrikirill** [comment]
The script doesn't use IPv4 that Synology provides as arguments. Instead of, it requests `https://api64.ipify.org?format=json` which returns an external `IPv4` or `IPv6` and than based on [the logic](https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain/blob/507ae45868c48c42c73c8179f8d2f73f6b88d43e/cloudflare.php#L367) it tries to update the `A record` for IPv4 OR  the `AAAA record` for IPv6.
Technically this can cause an issue if a zone has an A record but ipify returns an IPv6 address.
Looks like it needs to be a param probably by default use IPv4 with param select IPv6 
Do you agree ?

**Comment by mrikirill** [comment]
Hey guys,

The script didn't cover case with both records A and AAAA
Made the update  -> https://github.com/mrikirill/SynologyDDNSCloudflareMultidomain/pull/45

**Comment by priitliivak** [comment]
Works great. Thanks for the update.

**Comment by gozzilli** [comment]
Same. Thank you!
